[versions]
pkl = "0.26.+"
kotlin = "1.9.0"
junit = "5.10.0"
spotless = "6.25.0"

[libraries]
junitEngine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
junitParams = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }
pklCore = { group = "org.pkl-lang", name = "pkl-core", version.ref = "pkl" }

[plugins]
pkl = { id = "org.pkl-lang", version.ref = "pkl" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
