[versions]
pkl = "0.30.+"
kotlin = "2.2.20"
junit = "5.+"
spotless = "6.25.0"
junitPlatformLauncher = "1.+"

[libraries]
junitEngine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
junitParams = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }
junitPlatformLauncher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junitPlatformLauncher" }
pklCore = { group = "org.pkl-lang", name = "pkl-core", version.ref = "pkl" }
pklParser = { group = "org.pkl-lang", name = "pkl-parser", version.ref = "pkl" }

[plugins]
pkl = { id = "org.pkl-lang", version.ref = "pkl" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless"}
